version: '3.8'

services:
  floapi:
    build:
      context: .
      dockerfile: FloAPI/Dockerfile
    depends_on:
      - postgres
    environment:
      ConnectionStrings__StocksDB: "Host=floapi.database;Database=stocksdb;Username=postgres;Password=P@ssWord!23"
    ports:
      - "8080:8080"
      - "8081:8081"
  
  postgres:
    image: postgres:16.4
    container_name: floapi.database
    environment:
      POSTGRES_PASSWORD: P@ssWord!23
      POSTGRES_DB: stocksdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: